# Site settings
course_name: INF216 - Projeto e Implementação de Jogos Digitais
course_description: "Essa disciplina é uma introdução às técnicas fundamentais para a programação de jogos 2D e 3D. Os alunos são apresentados a conceitos de projeto de software, física, gráficos, inteligência artificial e áudio aplicados para o desenvolvimento de jogos. Espera-se que os alunos produzam um protótipo funcional em C++ para cada tópico abordado em aula, além de um projeto final. Os alunos utilizam ferramentas profissionais de desenvolvimento para simular um ambiente de trabalho real (como um estúdio de jogos), tendo a oportunidade de publicar um portfólio pessoal com os trabalhos desenvolvidos ao longo do curso."
course_semester: "2023/2"

semester_start: 2023-08-14T08:00
semester_end: 2023-12-18T08:00
lectures_hours: PVA102, Terça-feira, 10-12h
labs_hours: CCE416, Sexta-feira, 08-10h

baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://ufv-inf216.lucasnferreira.com/" # the base hostname & protocol for your site

schoolname: "Universidade Federal de Viçosa"
schoolurl: "https://www.ufv.br"
twitter_username: lucasnfe 

address: |
    Departamento de Informática
    Universidade Federal de Viçosa
    Viçosa, MG, Brasil

# Set your Google Analytics tracking ID (set up yours at http://www.google.com/analytics/)
# google_analytics: UA-XXXXXXXX-X

### Do not change the followings unless you know what you are doing ###

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
excerpt_separator: "<!--more-->"

include: ['_images', '_css']
exclude: ['develop']

dateformat: "%d/%m/%Y"
date_locale: pt

future: true
collections:
    events:
        output: true
    lectures:
        output: true
    labs:
        output: true
    assignments:
        output: true
    quizzes:
        output: true
    projects:
        output: true
    announcements:
        output: false

defaults:
  - scope:
      path: ""
      type: "assignments"
    values:
      layout: "assignment"
